# Generated by Django 6.0 on 2026-02-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(help_text='Unique train number, e.g. 12301', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Train name, e.g. Rajdhani Express', max_length=120)),
                ('source', models.CharField(help_text='Departure station name', max_length=120)),
                ('destination', models.CharField(help_text='Arrival station name', max_length=120)),
                ('departure_time', models.DateTimeField(help_text='Scheduled departure date & time')),
                ('arrival_time', models.DateTimeField(help_text='Scheduled arrival date & time')),
                ('total_seats', models.PositiveIntegerField(help_text='Total number of seats on this train')),
                ('available_seats', models.PositiveIntegerField(help_text='Currently available seats for booking')),
            ],
            options={
                'db_table': 'trains',
                'ordering': ['departure_time'],
                'indexes': [models.Index(fields=['source', 'destination'], name='idx_train_src_dest'), models.Index(fields=['train_number'], name='idx_train_number'), models.Index(fields=['source'], name='idx_train_source'), models.Index(fields=['destination'], name='idx_train_destination'), models.Index(fields=['departure_time'], name='idx_train_departure')],
            },
        ),
    ]
