# Generated by Django 6.0 on 2026-02-27 08:11

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(help_text='HTTP method (GET, POST, PUT, DELETE, etc.)', max_length=10)),
                ('path', models.CharField(help_text='Request URL path', max_length=500)),
                ('status_code', models.IntegerField(help_text='HTTP response status code')),
                ('user_id', models.IntegerField(blank=True, help_text='ID of the authenticated user (if any)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('query_params', models.JSONField(blank=True, default=dict, help_text='URL query parameters')),
                ('request_body', models.JSONField(blank=True, default=dict, help_text='Request body payload (sanitised)')),
                ('response_time_ms', models.FloatField(default=0, help_text='Response time in milliseconds')),
                ('user_agent', models.CharField(blank=True, default='', help_text='Client User-Agent string', max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the request was logged')),
            ],
            options={
                'db_table': 'api_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
