# Generated by Django 6.0 on 2026-02-27 08:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_booked', models.PositiveIntegerField(help_text='Number of seats reserved in this booking', validators=[django.core.validators.MinValueValidator(1)])),
                ('booking_time', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the booking was created')),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', help_text='Current status of the booking', max_length=12)),
                ('pnr', models.CharField(editable=False, help_text='Auto-generated PNR number', max_length=10, unique=True)),
                ('train', models.ForeignKey(help_text='The train for which this booking was made', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trains.train')),
                ('user', models.ForeignKey(help_text='The passenger who made this booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-booking_time'],
                'indexes': [models.Index(fields=['user', 'booking_time'], name='idx_booking_user_time'), models.Index(fields=['pnr'], name='idx_booking_pnr'), models.Index(fields=['train', 'status'], name='idx_booking_train_status'), models.Index(fields=['status'], name='idx_booking_status')],
            },
        ),
    ]
